// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mavztuehooniwlpnzzko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hdnp0dWVob29uaXdscG56emtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMzg0NDUsImV4cCI6MjA2OTcxNDQ0NX0.A9a2sWW-nhMyt0pL40W4l8bbIv0_XYgKHfJt9DO34Yk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});